[FileDialog]
history=file:///media/dylansavoia/storage/1_Downloads/ARCHIVE_drive-download-20190329T173648Z-001, file:///media/dylansavoia/storage/1_Downloads/Camera/BKP, file:///media/dylansavoia/storage/1_Downloads/Camera/workspace/BKP, file:///home/dylansavoia/Downloads, file:///media/dylansavoia/HDD/Camera/photos/other, file:///media/dylansavoia/HDD/Camera/photos
lastVisited=file:///media/dylansavoia/HDD/Camera/photos
qtVersion=5.12.3
shortcuts=file:, file:///home/dylansavoia
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0;\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
