#!/bin/bash
cmd="$1"
dev="$2"
devs=('desktop' 'laptop' 'termux' 'server')

# Auto-detect
if [ -n "${ANDROID_ROOT}" ];              then dev='termux'
elif [ -n "`grep ARM /etc/os-release`" ]; then dev='server'
fi

# Choose Device
if [[ "$dev" == "" ]]; then
    echo "Choose device:"
    echo ${devs[*]} | tr ' ' '\n' | nl -v 0 -w 1
    echo -n ">>> "
    read dev

    if [ $dev -ge ${#devs[*]} ]; then
        echo "Invalid device. Run again"
        exit 1
    fi

    dev=${devs[$dev]}
fi

echo -e "Selected Device:\t$dev"

case "$cmd" in
    "setup" )
        case "$dev" in
            "termux" ) source .scripts/setup_termux.sh;;
            "server" ) source .scripts/setup_server.sh;;
            * ) echo "Setup not available for $dev"
        esac
    ;;

    "collect" ) source .scripts/collect.sh "$2" ;;
    "restore" )
        case "$dev" in
            "desktop"|"laptop" ) source .scripts/restore_pc.sh $dev;;
            "termux" )           source .scripts/restore_termux.sh;;
            "server" )           source .scripts/restore_server.sh;;
            *) echo "Restore not available for $dev"
        esac
    ;;

    *)
        echo "Usage: dotfiles [setup|collect|restore]"
    ;;
esac
