#!/bin/bash
cmd="$1"
devs=('desktop' 'laptop' 'termux' 'server')
vardir=./variables
themes=(`ls -1d "$vardir"/*/ | cut -d / -f3`)

default_theme=`cat .current_theme`

case "$cmd" in
    "collect" ) source .scripts/collect.sh "$2" ;;
    "restore" )
        if [[ "$2" == "" ]]; then
            echo "Choose device:"
            echo ${devs[*]} | tr ' ' '\n' | nl -v 0 -w 1
            echo -n ">>> "
            read dev

            if [ $dev -ge ${#devs[*]} ]; then
                echo "Device Out Of Boundaries"
                exit 1
            fi
            dev=${devs[$dev]}
        else
            dev=$2
        fi

        # Choose Theme
        if [[ "$3" == "" ]]; then
            echo "Choose Theme (Default \"$default_theme\"):"
            echo ${themes[*]} | tr ' ' '\n' | nl -v 0 -w 1
            read theme

            if [[ $theme == "" ]]; then
                theme=$default_theme
            elif [ $theme -ge ${#themes[*]} ]; then
                echo "Theme Out Of Boundaries"
                exit 1
            else
                theme=${themes[$theme]}
            fi
        fi

        echo -e "\nSelected Theme:\t\t$theme"
        echo -e "Selected Device:\t$dev\n"

        ## Save current theme name
        echo "$theme" > .current_theme

        case "$dev" in
            "desktop"|"laptop" ) source .scripts/restore_pc.sh $dev $theme;;
        esac

        ;;
    *)
        echo "Usage: dotfiles [setup|collect|restore]"
    ;;
esac
