#!/bin/bash

xdotool search Playlist windowfocus

for i in {1..2} ; do
    sleep 0.2
    xdotool mousemove 0 0
    sleep 0.2
    xdotool mousemove 850 250
    sleep 0.2
    xdotool type --delay 100 "f30"
    sleep 0.2
    xdotool type --delay 100 "f"
    sleep 0.2
    xdotool type --delay 100 "remove"
    sleep 0.2
    xdotool type --delay 100 "3"
done

