#!/bin/bash
if [[ "$1" == "download" || "$1" == "d" ]]; then
    youtube-dl -x --audio-format mp3 --audio-quality 0 https://www.youtube.com/playlist?list=PLtO5M4JOGPH4tzQVb61jCjukLQG-OkS9I

elif [[ "$1" == "update" || "$1" == "u" ]]; then
    # Update Tags
    echo "Writing Tags..."
    python ~/.local/scripts/mp3_tags.py .

    # Normalize
    echo "Do you want to normalize? (Y|n)";
    read answ
    [[ "$answ" == "" || "$answ" == "y" ]] && mp3gain -r *

    # Copy Tracks to phone
    echo "Do you want to copy tracks on phone? (Y|n)";
    read answ

    phoneDir="/media/dylansavoia/phone"
    if [[ "$answ" == "" || "$answ" == "y" ]]; then
        echo "Copying Tracks to phone..."
        mountpoint -q $phoneDir || jmtpfs $phoneDir
        [[ $? -ne 0 ]] && return
        cp * "$phoneDir/SD card/Music/"
        [[ $? -ne 0 ]] && (echo "Copy Failed"; return)

        # Update current_tracks
        ls "$phoneDir/SD card/Music" > current_tracks.txt
        rclone copy -v current_tracks.txt pcloud:/
        awk -F ' - ' '{gsub(/\(.+\)/, "", $2); print $2 }' current_tracks.txt > "$phoneDir/SD card/Android/lib.txt"
        rm current_tracks.txt
    fi

    # Update Library
    echo "Copying to Library"
    rclone -v copy . pcloud:Library

fi

