[colors.normal]
black = "{{black0}}"
blue = "{{blue0}}"
cyan = "{{cyan0}}"
green = "{{green0}}"
magenta = "{{magenta0}}"
red = "{{red0}}"
white = "{{white0}}"
yellow = "{{yellow0}}"

[colors.bright]
black = "{{black1}}"
blue = "{{blue1}}"
cyan = "{{cyan1}}"
green = "{{green1}}"
magenta = "{{magenta1}}"
red = "{{red1}}"
white = "{{white1}}"
yellow = "{{yellow1}}"

[colors.primary]
background = "{{bkg}}"
foreground = "{{fg}}"

[env]
TERM = "xterm-256color"

[font]
size = {{fontSize}}

[font.glyph_offset]
x = 0
y = 5

[font.normal]
family = "Liberation Mono"

[font.offset]
x = 0
y = 10

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 3
y = 0
