[drive]
type = drive
client_id = 
client_secret = 
token = {"access_token":"ya29.Gl36Bu_GQB8O1ZIy25IPK5svOoVjo4ZcTluDpHzK9oQIe6ehBVofG1fFQ_XL3F2YGPMJfY0bTR2IEE5cQW3VCnzxLkH649QgIiNM9W8tl7LMjZhFP-1o0-I9JLiwvqI","token_type":"Bearer","refresh_token":"1/lntH1ALLOETHv3sZ03tt0UyqYvZ1YEMSWuo2DDGQ7Pg","expiry":"2019-04-29T14:28:23.788852532+02:00"}

[pi]
type = sftp
host = dylansavoia.sytes.net
user = dylansavoia
port = 
pass = P6LljF3b18bn-4XWCrY4MIxFvZfGkTWaQ0o
key_file = 

[pcloud]
type = pcloud
token = {"access_token":"rf0aZDnONSzyJXpmZkgofI7ZaEeEaIPX8xmq9nRgJEcMxHVp1GqV","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}

