#! /bin/sh
# Autorun
sxhkd &
compton --config ~/.config/compton/compton.conf &
feh --bg-fill ~/.config/bspwm/wallpaper.jpg
dunst &
polybar mainbar & 

# Monitors and Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Config
bspc config border_width         1
bspc config window_gap          15
# bspc config border_radius       3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config external_rules_command ~/.config/bspwm/ext_rules.sh

# Rules
bspc rule --add qutebrowser      desktop='6'      follow=on
bspc rule --add firefox          desktop='6'      follow=on
