#!/bin/bash

if xrandr | grep "HDMI-1 disconnected"; then
    xrandr --output DP-1 --off --output HDMI-1 --off --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-2 --off
else
    xrandr --output DP-1 --mode 1920x1080 --pos 0x0 --rotate left --output HDMI-1 --primary --mode 2560x1440 --pos 1080x232 --rotate normal --output eDP-1 --off --output HDMI-2 --off
fi
