#!/usr/bin/env sh

if xrandr | grep "HDMI-1 disconnected"; then
    export MONITOR="eDP-1"
else
    export MONITOR="HDMI-1"
fi


killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar mainbar
