#!/bin/bash

str_options="suspend\nshutdown\nrestart"
option=$(echo -e $str_options | rofi -columns 3 -dmenu -p "Power: ")

if [ $option == "suspend" ]; then
    notify-send "Suspending..."
    systemctl suspend
elif [ $option == "shutdown" ]; then
    notify-send "Shutting down..."
    shutdown now
elif [ $option == "restart" ]; then
    notify-send "Restarting..."
    shutdown -r now
fi
