#!/bin/bash
readonly ID_PREVIEW="preview"

if [ -e "$FIFO_UEBERZUG" ]; then
    if [[ "$1" == "draw" ]]; then

        if [[ $7 == *.pdf ]]; then
            name=${7:0:-4}
            test -e "/tmp/$name.jpg" || convert -density 100 "$6/$7"[0] -flatten "/tmp/$name.jpg"
            img="/tmp/$name.jpg"
        else
            img="$6/$7"
        fi

        declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                           [x]="$2" [y]="$3" [width]="$4" [height]="$5" [scaler]="contain" \
                           [path]="$img") \
            > "$FIFO_UEBERZUG"
    else
        declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
            > "$FIFO_UEBERZUG"
    fi
fi
