#!/bin/bash

ids=`xprop -root | grep "_NET_CLIENT_LIST(WINDOW)" | tr ',' '\n' | egrep -o "0x[a-f0-9]+"`
tokill=''

for i in $ids; do
    proc=`xprop -id $i`
    # name=`echo "$proc" | grep -Po '_NET_WM_NAME.+"\K[^"]+'`
    name=`echo "$proc" | grep '_NET_WM_NAME' | grep -Po '"\K[^"]+'`
    pid=`echo "$proc" | grep '_NET_WM_PID' | egrep -o '[0-9]+'`
    tokill=`echo "$tokill$pid\t$name\n"`
done


tokill=`echo -e "$tokill" | rofi -multi-select -dmenu -p "Kill"`
echo -e "$tokill" | cut -d $'\t' -f1 | xargs -n1 kill
