#!/bin/bash

### Info ######################################
#   .pcache (prettified cache) is a list of prettified_names
#   When shown, an index is prepended to each item So that you obtain:
#   | N | icon | prettified_name | 
#
#   N is then used to access .cache at the Nth record:
#   | category | full_name |
#   
#   This record is the format used in the "Run" Section.
#   Category can be:
#   - 0: Other (including not in cache)
#   - 1: File
#   - 2: Terminal
#
#   Every command followed by a ';' is executed opening a terminal
#   es. 'htop;'
#
#   Shortcuts are defined in their own file with the following structure:
#   icon : alias : command


### Create ####################################
config="$HOME/.config/laser/"
cache="/tmp/.laser_cache"
pcache="/tmp/.laser_pcache"

rc=`cat "$config/laserrc"`

[[ -e $config ]] || mkdir $config

# Get section <name> from rc variable (the config file)
function from_rc() {
    local res=`echo "$rc" | awk -v name="$1" '
        BEGIN {p=0}
        /^$/ {p=0}
        {if (p==1) print $0}
        $0 ~ name {p=1}'`

    echo "$res"
}

function generate () {
    # Shortcuts
    shrt=$(from_rc Shortcuts)

    shrt_c=`echo "$shrt" | cut -d ':' -f 3- | awk 'BEGIN{OFS="\t"}{print "0", $0}'`
    shrt_p=`echo "$shrt" | awk -F ':' '{print $1 "\t" $2}'`

    # Binaries
    # minipath=( /usr/local/bin /usr/bin )
    # bins=`echo ${minipath[*]} | tr ' ' '\n' | xargs -n 1 ls -1`
    bins=`comm -1 -2 <(cat ~/.bash_history | awk '{print $1}' | sort | uniq) <(ls -1 /usr/bin)`
    echo "$bins"
    bins_c=`echo "$bins" | awk 'BEGIN{OFS="\t"}{print "0", $0}'`
    bins_p=`echo "$bins" | awk '{print "" "\t" $0}'`

    # Files and Dirs
    paths=$(from_rc Directories)
    paths=`echo "$paths" | tr '\n' ' '`

    files=`find $paths -printf "%A@\t%y\t%d\t%h/%f\n" |
        awk -F '\t' '
            $2 == "d" {print 9999999999 - $3, "\t\t"$4}
            $2 != "d" {
                sub(/\.[0-9]+/, "", $1);
                print $1 "\t\t" $4;
            }' | sort -r -n -k 1` 

    fdirs_c=`echo "$files" | awk -F '\t' 'BEGIN{OFS="\t"}{print "1", $3}'` 

    fdirs_p=`echo "$files" | awk -F '\t' '{
        print $2 "\t" $3
    }'`

    echo -e "$shrt_c\n$bins_c\n$fdirs_c" > "$cache"
    echo -e "$shrt_p\n$bins_p\n$fdirs_p" > "$pcache"

}

( [[ ! -e $cache ]] || [[ $1 == "-r" ]] ) && generate
[[ $1 == "-r" ]] && exit

### Show #######################################
# ...in prettified form
sel=`rofi -terminal xst -dmenu -input '/tmp/.laser_pcache' -format 'd s' -i -p "Run"` 

## If in list select original line from file,
## otherwise print directly.
echo "$sel"
n=`echo $sel | awk '{print $1}'` 

if [[ $n -ne 0 ]]; then
    sel=`sed -ne "$n p" $cache`
fi


### Run #########################################
split=( $sel )
category=${split[0]}
name="${split[*]:1: ${#split[*]}}"

echo "Cat: $category"
echo "Name: $name"

# Check if shell
if [[ ${name: -1} == ";" ]]; then
    name=${name:0: -1}
    category='t'
else
    t=$(from_rc Terminal)
    cmd=($name)
    for i in $t; do
        if [[ $i == $cmd ]]; then
            category='t'
            break
        fi
    done
fi

[[ ${#name} -gt 2 ]] && launcher "$category" "$name"
