#!/bin/bash

### Info ######################################
#   .pcache (prettified cache) is a list of prettified_names
#   When shown, an index is prepended to each item So that you obtain:
#   | N | icon | prettified_name | 
#
#   N is then used to access .cache at the Nth record:
#   | category | full_name |
#   
#   This record is the format used in the "Run" Section.
#   Category can be:
#   - 0: Other (including not in cache)
#   - 1: File
#   - 2: Binaries
#
#   Every command followed by a ';' is executed opening a terminal
#   es. 'htop;'
#
#   Shortcuts are defined in their own file with the following structure:
#   icon : alias : command


### Create ####################################
config="$HOME/.config/laser/"
cache="/tmp/.laser_cache"
pcache="/tmp/.laser_pcache"

rc=`cat "$config/laserrc"`

[[ -e $config ]] || mkdir $config

# Get section <name> from rc variable (the config file)
function from_rc() {
    local res=`echo "$rc" | awk -v name="$1" '
        BEGIN {p=0}
        /^$/ {p=0}
        {if (p==1) print $0}
        $0 ~ name {p=1}'`

    echo "$res"
}

function generate () {
    # Shortcuts
    shrt=$(from_rc Shortcuts)

    shrt_c=`echo "$shrt" | cut -d ':' -f 3- | awk 'BEGIN{OFS="\t"}{print "0", $0}'`
    shrt_p=`echo "$shrt" | awk -F ':' '{print $1 "\t" $2}'`

    # Binaries
    minipath=( /usr/local/bin /usr/bin )
    bins=`echo ${minipath[*]} | tr ' ' '\n' | xargs -n 1 ls -1`

    bins_c=`echo "$bins" | awk 'BEGIN{OFS="\t"}{print "2", $0}'`
    bins_p=`echo "$bins" | awk '{print "" "\t" $0}'`

    # # Files and Dirs
    paths=$(from_rc Directories)
    paths=`echo "$paths" | tr '\n' ' '`

    files=`find $paths -name ".*" -prune -o -printf "%A@\t%y\t%d\t%h/%f\n" |
        awk -F '\t' '
            $2 == "d" {print 9999999999 - $3, "\t\t"$4}
            $2 != "d" {
                sub(/\.[0-9]+/, "", $1);
                print $1 "\t\t" $4;
            }' | sort -r -n -k 1` 

    fdirs_c=`echo "$files" | awk -F '\t' 'BEGIN{OFS="\t"}{print "1", $3}'` 

    fdirs_p=`echo "$files" | awk -F '\t' '{
        match($3, /((\/[^\/]+){1,3}\/?)$/);
        print $2 "\t" substr($3, RSTART, RLENGTH)
    }'`

    echo -e "$shrt_c\n$bins_c\n$fdirs_c" > "$cache"
    echo -e "$shrt_p\n$bins_p\n$fdirs_p" > "$pcache"

}

( [[ ! -e $cache ]] || [[ $1 == "-r" ]] ) && generate
[[ $1 == "-r" ]] && exit

### Show #######################################
# ...in prettified form
sel=`nl -w 4 -s '  ' $pcache | rofi -terminal xst -dmenu -i -p "Run"` 

## If in list select original line from file,
## otherwise print directly.
n=`echo $sel | awk '{print $1}'` 

if [[ $n =~ ^[0-9]+$ ]]; then
    sel=`sed -ne "$n p" $cache`
else
    sel=`echo "0 $sel"`
fi


### Run #########################################

# Check if shell

split=( $sel )
category=${split[0]}
name="${split[*]:1: ${#split[*]}}"

echo "Cat: $category"
echo "Name: $name"

[[ ${#name} -lt 3 ]] && exit

if [[ ${name: -1} == ";" ]] || [[ $category == 2 ]]; then
    [[ ${name: -1} == ";" ]] && name=${name:0: -1}

    guis=$(from_rc GUIs)
    cmd=($name)
    for i in $guis; do
        if [[ $i == $cmd ]]; then
            $name &
            cmd=""
            break
        fi
    done
    [[ $cmd == "" ]] || $TERMINAL -c "$name" -e bash -ic "$name" #; read -p 'Press to continue... '"
else
    # first try matching by filename or pathname
    case "${name,,}" in
        http*)
            $BROWSER "$name" &
            ;;
        *.txt)
            $TERMINAL $EDITOR "$name" &
            ;;
        *.pdf | *.epub)
            zathura "$name" &
            ;;
        *.mp3)
            $TERMINAL mpg123 -opulse "$name" &
            ;;
        *.od[tsp]|*.doc|*.docx|*.ppt|*.pptx|*.xls|*.xlsx)
            libreoffice "$name" &
            ;;
        *)
            # then try matching by mimetype
            mimetype=$(file -Lb --mime-type "$name")
            case "$mimetype" in
                # text/html)
                #     $BROWSER "$name" &
                #     ;;
                text/* | inode/x-empty | message/rfc822)
                    $TERMINAL $EDITOR "$name" &
                    ;;
                inode/directory)
                    $TERMINAL vifm "$name"
                    ;;
                image/*)
                    sxiv "$name" &
                    ;;
                *)
                    exit 1
                    ;;
            esac
            ;;
    esac
fi
