#!/bin/bash

sel=$(
        join -t $'\t' <(lsblk -l --output NAME,SIZE | nl) <(lsblk -lpb --output SIZE,TYPE,MOUNTPOINT | nl) |
        awk '/part $/ && $4 > 4096 {printf("%s\t\t%s\n"), $2, $3}' |
        rofi -dmenu |
        awk '{print $1}'
    )
[[ "$sel" == "" ]] && return

echo "Where do you want to mount $sel?"
read mpoint

[[ "$mpoint" == "" ]] && mpoint="default"

mpoint="$mpoint"
mountpoint -q $mpoint && umount $mpoint

mount "$sel" "$mpoint"
vifm "/media/dylansavoia/$mpoint"
