#!/bin/bash

tmpfile='/tmp/screenshot.jpg'
import "$tmpfile"

if [[ $1 == '--ocr' ]]; then
    tesseract "$tmpfile" "${tmpfile}"
    sed -i '/^$/d' "${tmpfile}.txt"
    xclip -selection clipboard -i "${tmpfile}.txt"
    notify-send -i "$HOME/.config/awesome/icons/screenshot.svg" 'Text Copied To Clipboard.'
else
    xclip -selection clipboard -target 'image/jpg' -i "$tmpfile"
    notify-send -i "$HOME/.config/awesome/icons/screenshot.svg" 'Screenshot Taken.'
fi
